### ISSUE TITLE
Regards to PixelDev's Ask

### ISSUE THREAD

**Issue by Connorado07** [BradBot1/LifeSteal#5]
I am helping develop a modified version of this plugin with PixelDev990. I was wondering how you got around the required net.minecraft.util.Identifier with giving it 	`public Config() { super(new Identifier(Constants.ID, "lifesteal")); }`. How are you doing that? It keeps throwing an error where its asking for new.minecraft.util.Identifier and how Constants.ID does not satisfy those requirements.

**Comment by BradBot1** [comment]
> public Config() { super(new Identifier(Constants.ID, "lifesteal")); }

If you look at the code you provided you will see its wrapped in an identifier constructor call, this is because [Constants.ID](https://github.com/BradBot1/BradsFabricApi/blob/2d42e541b85dae0cc79cc75171fcc4f093150255/src/main/java/com/bb1/fabric/bfapi/Constants.java#L14) only returns a string

This all means that `new Identifier(Constants.ID, "lifesteal")` will result in an identifier of `bfapi:lifesteal`

I must ask you to refrain from using [Constants (click me for source)](https://github.com/BradBot1/BradsFabricApi/blob/master/src/main/java/com/bb1/fabric/bfapi/Constants.java) as it is not a class provided by LifeSteal itself but [BFAPI](https://github.com/BradBot1/BradsFabricApi).
The reason for this is that the first part of the identifier is used as the sub directory to save the config under, so i ask that you please use your own to avoid conflicting with the base LifeSteal

**Comment by BradBot1** [comment]
Oh also try to use a differing mod id and set `lifesteal` to be in the `conflicts` section of your fabric.mod.json this will prevent people from using your version alongside the base <3
