### ISSUE TITLE
I don't under stand how to command works

### ISSUE THREAD

**Issue by NeoNotNeon** [BradBot1/LifeSteal#9]
Idk how the command works so could you re-message me the command and use the username N3o_V2 and 2 hearts?

**Comment by BradBot1** [comment]
By default the alias is `lifesteal` so that's what I will use

I am going to assume that the player isn't online so I have used [NameMC](https://namemc.com/profile/N3o_V2.1) to grab the users UUID (b64b6ee631f74436a48c99c724adad92)

Also I am unsure if you want to loose, gain or set the user to only have 2 hearts so I will give you the commands for all of them

To take two hearts you can preform:
`/lifesteal set b64b6ee631f74436a48c99c724adad92 4`

To give two hearts you can preform:
`/lifesteal set b64b6ee631f74436a48c99c724adad92 -4`

To set the players health to 2 hearts you can preform:
`/lifesteal set b64b6ee631f74436a48c99c724adad92 16`

Hope that helps <3
